### ISSUE TITLE
Need help to use this to update PIC18F57K42

### ISSUE THREAD

**Issue by ashasingh2018** [jaromir-sukuba/a-p-prog#1]
Hi,
My system consists of a 4Duino (has ATmega32U4, AVR) and PIC18F57K42.  The 
4Duino talks to the PIC via I2C. 
The 4Duino has a USB interface that can talk to the PC

I use Arduino IDE to build the 4Duino code and flash the 4Duino.
I use a JTAG programmer to flash the PIC code (uses ICD 3 and MPLAB v4.15). But to do this we have to open the encasing to get to the JTAG pins which is why we want to be able to do the PIC firmware upgrade without opening the encasing.

I looked at your programming tool here and I was wondering if I would be able to use it.
Can I use the 4Duino with your pp.ino to program the pic ?

I tried to build pp.ino using the IDE but it failed because of the macros  below -- it cannot find these.
     UBRR0H = ((_UBRR) & 0xF00);
    UBRR0L = (uint8_t) ((_UBRR) & 0xFF); 
     UCSR0B |= _BV(TXEN0);
     UCSR0B |= _BV(RXEN0);

Any help and suggestion would be appreciated very much. Thanks, Asha

**Comment by jaromir-sukuba** [comment]
The firmware is using Atmega328 specific IO access. It can be probably ported to USB based devices, but it will not be trivial and I'm not planning to do this in near future.
For now I'm closing this issue.
