### ISSUE TITLE
Can confirm PIC16F18313 works

### ISSUE THREAD

**Issue by DerWaldi** [jaromir-sukuba/a-p-prog#11]
This is a very nice and useful programmer.
I have just used it to flash a PIC16F18313, so I can confirm that these chips work, too.
I am creating this issue, because I thought you might want to add a tested check in the ReadMe.

Thank you for sharing your project!

Have a good time,
Sebastian

**Comment by jaromir-sukuba** [comment]
Thank you, I'll update readme.
