### ISSUE TITLE
Visual form for Windows

### ISSUE THREAD

**Issue by Cystor** [jaromir-sukuba/a-p-prog#12]
Hi,
I have worked on a visual application for Windows to help the users to operate your programmer more easily.
Its was building using Lazarus and its already working. Just need to be checked on Linux.

I want to colaborate with this visual form in your project, let me know if you like it.
Below there's a screenshot that shows how it is:

![prog_screenshot](https://user-images.githubusercontent.com/74105086/98444338-df444d00-20ef-11eb-8aba-8bb40a8a649a.png)

**Comment by jaromir-sukuba** [comment]
Hello, this looks great, thank you for your work.
Is this publicly available? I'd like to try it out.
I can put the link to your work into readme, for others to try and use.

**Comment by Cystor** [comment]
Thanks a lot.
This application is not publicly available yet.
I was just waiting for your answer, because the code is very related to your (actually it needs your executable).
I can create a new repository of source code and executable for others to use it, or if you want, you can add to this repository too.
I look forward to your reply.

**Comment by jaromir-sukuba** [comment]
Did you move any further with this application?

**Comment by Cystor** [comment]
> Did you move any further with this application?

The application seems work well.
I was just waiting for your permision to upload it in a new repository.
That is because actually in the current state of the project it still needs to use your executable in background.

**Comment by jaromir-sukuba** [comment]
I'd love to see it public and add link to your project to the project description.

**Comment by Cystor** [comment]
Thanks, [check here](https://github.com/Cystor/PicuinoProgrammer) my project.
And please, let me know if there's something wrong.
