### ISSUE TITLE
Arduino Mega as the programmer (the pins are differents)

### ISSUE THREAD

**Issue by Cystor** [jaromir-sukuba/a-p-prog#13]
Hi,
I was using Arduino Mega to test this programmer and the pins are subtly differents.
I think that include the pins in your docs can help the people a lot.

Here's the complete modification i've made:
[Micro Progmeter.docx](https://github.com/jaromir-sukuba/a-p-prog/files/5504952/Micro.Progmeter.docx)

Below is the table with pins for the Arduino Mega (just for previews):

| Arduino UNO pin | Arduino MEGA pin | AVR pin | Target PIC pin |
| ------------------ | ------------------- | -------- | -------------- |
| GND                    | GND                      | GND      | GND              |
| 5V                       | 5V                         | VDD       | VDD              |
| A3                       | 34                         | PC3        | MCLR            |
| A1                       | 36                         | PC1        | PGD              |
| A0                       | 37                         | PC0        | PGC              |

Thanks.

**Comment by jaromir-sukuba** [comment]
Thanks for contribution, I'll update readme document.
