### ISSUE TITLE
[FEATURE REQUEST] Support for 12F629/12F675/12F683 and 16F628A/16F676

### ISSUE THREAD

**Issue by silvioprog** [jaromir-sukuba/a-p-prog#15]
Those devices above are very popular, so it would be nice to add support for them. 😃👍

**Comment by thinhx2** [comment]
> Những thiết bị ở trên rất phổ biến, vì vậy sẽ rất tốt nếu bạn thêm hỗ trợ cho chúng. 😃👍

They use high voltage (12v) to program instead use low voltage (5v)

**Comment by jaromir-sukuba** [comment]
Those MCUs don't support low voltage programming and need higher than 5V on MCLR pin to enter programming mode. Those are not and will not be supported unless hardware is modified.
What more, with the older PICs there is a lot of programming algorithm variations, complicating the work.
