### ISSUE TITLE
Exchanged Device Id between PIC18F47Q10 and PIC18F27Q10, and a modification of .ino

### ISSUE THREAD

**Issue by SuperFabius** [jaromir-sukuba/a-p-prog#18]
Hi, I've successfully used your programmer on linux (with a common Arduino UNO) to flash a PIC18F47Q10!

Please note that the Device Id of PIC18F27Q10 and PIC18F47Q10 are exchanged, so I've corrected at first them in your "pp3_devices.dat" files.

I've also noticed that  the MCLR/VPP pin (A3) is normally at HIGH level. This can be an issue when connecting your programmer to self-powerd boards. I've checked on both the MPLAB Pickit 4 and MPLAB SNAP programmers and they leave the MCLR/VPP pin at GND or 3-stated.

So I've modified your .ino and added a small switch on A2 so I can put your programmer into a "stand-by" state with all the ICSP pin at GND (or 3-stated) . This allows to connect safely the ICSP cable with an un-powered target board while the Arduino Uno is powered. Then I can power the target board and change the position of the switch to let  the programmer operate as intended.

After the programming I do in sequence: set the switch to "stand-by" again, reset the Arduino UNO, un-power the target board, disconnect the ICSP cable, and finally un-power the Arduino UNO.

Here the changed part at the beginning of you "int main" function:

.....

int main (void)
{

  pinMode(13, OUTPUT);
  pinMode(A2, INPUT_PULLUP);
  while (digitalRead(A2))
  {
    digitalWrite(13, HIGH);
    _delay_ms(200);
    digitalWrite(13, LOW);
    _delay_ms(200);
  }

.....

The blinking Led of the Arduino UNO is used to give the feedback that the programmer is in the "stand-by" state, and the connection or disconnection to/from the target board is safe.

Thanks for this beautiful programmer!

I'll use it to give a simple and cheap way to program the PIC18F47Q10 MCU used inside my 68k-MBC board.

Here a couple of images of my Arduino Uno and the "ICSP adapter boad":

https://i.postimg.cc/L4PDWjcP/20210417-155447.jpg

https://i.postimg.cc/zvTkR1C7/20210417_155718.jpg

Regards.

**Comment by jaromir-sukuba** [comment]
Thank you for your contribution, I merged it.
