### ISSUE TITLE
Programming PIC18F14K50

### ISSUE THREAD

**Issue by matangk** [jaromir-sukuba/a-p-prog#5]
Great work so far!
Any reason it wont work with PIC18F14K50?
Its not on the supported device list..
Cheers!

**Comment by jaromir-sukuba** [comment]
This one requires either high voltage on MCLR or wiggling with PGM pin, that is older variant of low voltage programming. 
I decided to support only newer low voltage programming PIC types (starting ~ 10 years ago), so 14K50 will not be supported any time soon.
