### ISSUE TITLE
facing problem while flashing PIC16F18875

### ISSUE THREAD

**Issue by embhobbb** [jaromir-sukuba/a-p-prog#9]
i am using your programmer to flash PIC16F18875 but i am getting error as follows.
`E:\DIY\Programmer\PIC Programmer using Arduino\picProg\sw>pp3.exe -c COM4 -s 1700 -t 16f18875 PwmGen.X.production.hex
PP programmer, version 0.99
Sleeping for 1700 ms while arduino bootloader expires
Wrong device ID: 0000, expected: 306d
Check for connection to target MCU, exiting now`

I could able to flash other controller PIC16F1847 but not this one. 
PIC16F18875 has MCLR resistor of 10K connected and pulled up to VDD. other than this i have not connected anything.

**Comment by jaromir-sukuba** [comment]
Could you, please, post a schematics diagram or photo of your setup?
16F18875 is among tested and proven ones; I'm not ruling out problem in my code, but I need more information to focus on the issue.
